config-version: 1
root-folder: 'objects'
modules-folder: null
snowflake-account: 'MDPVAJJ-NJB64163'
snowflake-user: '{{env_var("SNOWFLAKE_USER")}}'
snowflake-role: '{{env_var("SNOWFLAKE_ROLE")}}'
snowflake-warehouse: 'COMPUTE_WH'
snowflake-database: '{{env_var("SNOWFLAKE_DATABASE")}}'
change-history-table: '{{env_var("SNOWFLAKE_DATABASE")}}.PUBLIC.CHANGE_HISTORY'
vars:
  db: '{{env_var("SNOWFLAKE_DATABASE")}}'
  read_role: '{{env_var("SF_READ_ROLE")}}'

# config-version: 1
# root-folder: 'objects'
# modules-folder: null
# change-history-table: '{{env_var("SNOWFLAKE_DATABASE")}}.PUBLIC.CHANGE_HISTORY'
# vars:
#   db: '{{env_var("SNOWFLAKE_DATABASE")}}'
#   read_role: '{{env_var("SF_READ_ROLE")}}'
