account_name = "MDPVAJJ-NJB64163"
user         = "SUKHPREETSNOWFLAKE"
password     = "Qwertyuiop@1234567890"
role         = "ACCOUNTADMIN"
warehouse    = "COMPUTE_WH"

database_name            = "APP_DATABASE"
schema_name              = "EXTERNAL_STAGING"
env                      = "dev"
storage_integration_name = "S3_INT"
s3_bucket_arn            = "arn:aws:s3:::sukhpreet-data-bucket"
s3_bucket_path           = "arn:aws:s3:::sukhpreet-data-bucket/data/"
aws_role_arn             = "arn:aws:iam::265766932672:role/snowflake-s3-role"
stage_name               = "S3_EXTERNAL_STAGE"
stage_url                = "s3://sukhpreet-data-bucket/data/"
file_format_name         = "CSV_FILE_FORMAT"