account_name = "MDPVAJJ-NJB64163"
user         = "SUKHPREETSNOWFLAKE"
role         = "ACCOUNTADMIN"
warehouse    = "COMPUTE_WH"

database_name            = "TF_DATABASE"
schema_name              = "EXTERNAL_STAGING"
env                      = "dev"
storage_integration_name = "S3_INT_TF"
s3_bucket_arn            = "arn:aws:s3:::sukhpreet-data-bucket"
s3_bucket_path           = "arn:aws:s3:::sukhpreet-data-bucket/data/"
aws_role_arn             = "arn:aws:iam::265766932672:role/snowflake-s3-role"
stage_name               = "S3_EXTERNAL_STAGE"
stage_url                = "s3://sukhpreet-data-bucket/data/"
file_format_name         = "CSV_FILE_FORMAT"
warehouse_name           = "TF_APP_WH"
app_role_name            = "TF_APP_ROLE"
read_only_role_name      = "TF_READ_ONLY_ROLE"
