name: Terraform Plan

on:
  pull_request:
    branches:
    - dev
    - main
  push:
    branches:
    - dev
    - main
    paths:
    - terraform/**

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_account_name: ${{ secrets.SF_ACCOUNT }}
      TF_VAR_user: ${{ secrets.SF_USER }}
      TF_VAR_password: ${{ secrets.SF_PASSWORD }}
      TF_VAR_role: ${{ secrets.SF_ROLE }}
      TF_VAR_warehouse: COMPUTE_WH
      # TF_VAR_database_name: ${{ github.base_ref == 'main' && 'APP_DATABASE_PROD' || 'APP_DATABASE_DEV' }}
      # TF_VAR_warehouse_name: ${{ github.base_ref == 'main' && 'APP_WH_PROD' || 'APP_WH_DEV' }}
      # TF_VAR_app_role_name: ${{ github.base_ref == 'main' && 'APP_ROLE_PROD' || 'APP_ROLE_DEV' }}
      # TF_VAR_read_only_role_name: ${{ github.base_ref == 'main' && 'READ_ONLY_ROLE_PROD' || 'READ_ONLY_ROLE_DEV' }}

      # TF_VAR_env: ${{ github.base_ref == 'main' && 'production' || 'development' }}

    steps:

    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - run: terraform init

    - run: terraform fmt -check

    - run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: terraform/tfplan
