name: Terraform Apply

on:
  push:
    branches:
    - dev
    - main
    paths:
    - terraform/**

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
        - development
        - production

jobs:
  terraform-apply:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    env:
      TF_VAR_account_name: ${{ secrets.SF_ACCOUNT }}
      TF_VAR_user: ${{ secrets.SF_USER }}
      TF_VAR_password: ${{ secrets.SF_PASSWORD }}
      TF_VAR_role: ${{ secrets.SF_ROLE }}
      TF_VAR_warehouse: COMPUTE_WH

      TF_VAR_database_name: ${{ github.ref == 'refs/heads/main' && 'APP_DATABASE_PROD' || 'APP_DATABASE_DEV' }}
      TF_VAR_warehouse_name: ${{ github.ref == 'refs/heads/main' && 'APP_WH_PROD' || 'APP_WH_DEV' }}
      TF_VAR_app_role_name: ${{ github.ref == 'refs/heads/main' && 'APP_ROLE_PROD' || 'APP_ROLE_DEV' }}
      TF_VAR_read_only_role_name: ${{ github.ref == 'refs/heads/main' && 'READ_ONLY_ROLE_PROD' || 'READ_ONLY_ROLE_DEV' }}

      TF_VAR_env: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:

    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - run: terraform init

    - run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Terraform Outputs
      run: terraform output
